name: Release

on:
  release:
    types: [published]

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tar -czvf '${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.tar.gz' rules/
      - run: gh release upload '${{ github.event.release.tag_name }}' '${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.tar.gz'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
